name: Telegram Notification
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, closed, synchronize]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    environment:
      name: telegram

    steps:
      - name: send telegram message on push or pull request
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: "markdownv2"
          message: |
            *LMS Frontend Event*: _${{ github.event_name }}_

            ${{ github.actor }} created commit
            Commit message: _${{ github.event.commits[0].message }}_

            Repository: \`${{ github.repository }}\`

            [See changes](https://github.com/${{ github.repository }}/commit/${{github.sha}})
